### ISSUE TITLE
Call bind on datagram socket

### ISSUE THREAD

**Issue by andrewthad** [layer-3-communications/simple_producer#3]
This doesn't currently ever call `bind`, so there's no way it can receive anything. The way that `connect` works with datagram sockets is a little weird (since datagram sockets are connectionless), but it's discussed in various forums. The two important things are:

* `bind` is the real deal. `connect` is just trick for getting the kernel to filter things out from unwanted sources so that time isn't wasted copied the data to user space
* If you do use `connect`, you should use `recv`, not `recvfrom`, since you already know the source of the datagram.

**Comment by chessai** [comment]
Okay, that makes sense. I will implement this change when i get in the office.

**Comment by chessai** [comment]
resolved in a6bad7e
